version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: retroflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: retroflow
      POSTGRES_PASSWORD: retroflow_dev_password
      POSTGRES_DB: retroflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U retroflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: retroflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data: